# Generated by Django 4.0.4 on 2022-06-26 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_song_audio_link_remove_song_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, max_length=300, verbose_name='Текст обзора')),
            ],
            options={
                'verbose_name': 'Обзор',
                'verbose_name_plural': 'Обзоры',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-rating'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
        migrations.AddField(
            model_name='song',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.review', verbose_name='Обзор'),
        ),
    ]
